### ISSUE TITLE
query variables

### ISSUE THREAD

**Issue by coolcodecding** [SoftwareDefinedBuildings/mortar-analytics#12]
When making the query:

`meter_query = """SELECT ?temp_sensor WHERE { ?temp_sensor rdf:type brick:Outside_Air_Temperature_Sensor };"""`

it's clear, that I am looking for temperature sensors that are outside air temp sensors, where "Outside_Air_Temperature_Sensor" is the category that this kind of sensor is found with BRICK schema.

What I still didn't fully understand is, what variables (e.g. ?temp_sensor, ?meter) I can seach for.
For example:
Looking for Chilled Water Flow Sensor, my query would be the following, where the unclear part is XXXXX.

`meter_query = """SELECT ?XXXXX WHERE { ?temp_sensor rdf:type brick:Chilled_Water_Flow_Sensor };"""`

and following this query up: What else can I put instead of XXXXX?

And one last question:
How would the query look like, if I want the timeseries of all sensors in one particular building?

Thanks in advance for your support!

**Comment by gtfierro** [comment]
Hey @coolcodecding 

The names of the variables in the SPARQL queries don't have anything to do with what they contain after query execution. They're logical identifiers that let you tie properties, classes and other relationships together in the query.

This means that the query

```sparql
SELECT ?temp_sensor WHERE {
  ?temp_sensor rdf:type brick:Outside_Air_Temperature_Sensor
}
```

will return the same results as

```sparql
SELECT ?xyz WHERE {
  ?xyz rdf:type brick:Outside_Air_Temperature_Sensor
}
```

If you want different types of points, you need to change what the object of the `rdf:type` property is (e.g. `brick:Temperature_Sensor`). 

I definitely need a better tutorial that I can point people to, but if you consider a Brick model as a graph, then each line of the WHERE clause is a "pattern" of that graph. Have you seen https://querybuilder.mortardata.org/? That might help build an intuition for how the queries work

---

As to your last question, the query would be something like

```python
q = """SELECT ?sensorname ?sensortype WHERE {
  ?sensorname rdf:type/rdfs:subClassOf* brick:Sensor .
  ?sensorname rdf:type ?sensortype
};"""
```

If you put that into the `view` and `dataFrames` part of the Mortar query, then you can get all of the sensor data, and then use the view to determine which type each sensor is. I can throw together some sample code if its unclear how that might work.

Hope that helps!

**Comment by coolcodecding** [comment]
Thank you very much for the response! I appreciate the awesome response time! For the first part, it is much clearer than before.  I still struggle a bit with querying all datapoints for one building.

Checking the quality response of 
`q = """SELECT ?sensorname ?sensortype WHERE {
  ?sensorname rdf:type/rdfs:subClassOf* brick:Sensor .
  ?sensorname rdf:type ?sensortype
};"""`

I see `running on 103 sites`.

I used a code that worked well before and put the same query as above into `pymortar.View()` and defined `dataVars=["?sensorname", "?sensortype"]` in `pymortar.DataFrame()`. Also I defined `time_params = pymortar.TimeParams(
    start="2016-01-01T00:00:00Z",
    end="2019-01-01T00:00:00Z",)`

I can run `client.fetch(request)`, but get as `result.dataFrames`  only `[ ]` .
I have tried shorter time periods as well, with the same result.

What confuses me, is that the query is being "accepted" as correct and I get a list of all "relevant" sites, but i can not get the timeseries data with the same query.

Is there any mistake I made when putting things together? 


EDIT: I think it is clear now! I missunderstood your answer and expected another output! But it seems to work well now, after checking the view!
Thanks a lot!

**Comment by gtfierro** [comment]
I think you only want to include the `?sensorname` in the `dataVars` attribute. `?sensortype` will contain the types of the sensors, but `dataVars` only wants the names of the data streams (which are stored in `?sensorname`).

If you only want the data for one site, you can change the `sites` attribute of the FetchRequest:

```
site = ["ciee"]
```

Hope that helps! Glad you got it working
