### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by jli113** [SoftwareDefinedBuildings/mortar-analytics#15]
Having problems at login.

/srv/conda/envs/notebook/lib/python3.7/site-packages/pymortar/__init__.py in __init__(self, cfg)
     79         # FIX: comment this out to allow token to expire and see connection state
     80         if self._token is None:
---> 81             self._refresh()
     82 
     83     def _connect(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/pymortar/__init__.py in _refresh(self)
     99     def _refresh(self):
    100         logging.info("Generating a new JWT token. Your old token may have expired")
--> 101         response = self._client.GetAPIKey(mortar_pb2.GetAPIKeyRequest(username=self._cfg["username"],password=self._cfg["password"]))
    102         #print(response)
    103         self._token = response.token

/srv/conda/envs/notebook/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    824         state, call, = self._blocking(request, timeout, metadata, credentials,
    825                                       wait_for_ready, compression)
--> 826         return _end_unary_response_blocking(state, call, False, None)
    827 
    828     def with_call(self,

/srv/conda/envs/notebook/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    727             return state.response
    728     else:
--> 729         raise _InactiveRpcError(state)
    730 
    731 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1619425405.102890241","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1619425405.102883652","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"

**Comment by gtfierro** [comment]
I responded to your post on the Google forum, replicated here:

Unfortunately, due to some recent attempts to deanonymize the data, I had to take the interface down. I will be investigating better anonymization techniques that will be implemented in the relaunch of Mortar, hopefully some time this summer after I finish my dissertation. If your intended use of Mortar cannot wait, please send me an email directly and I would be happy to help work something out.
