### ISSUE TITLE
Query Builder Website not working

### ISSUE THREAD

**Issue by rambalachandran** [SoftwareDefinedBuildings/mortar-analytics#9]
I'm trying to create a simple graph as described in mortar tutorial which relates a `VAV` to a `Supply Air Flow Sensor` and `Supply Air Flow Setpoint`. However when I open the interactive Brick query builder website (https://querybuilder.mortardata.org/). There is an option to start from VAV, but there is no option to add the subsequent child nodes that are related to VAV. I used both chrome and edge but I face the same issue.

**Comment by gtfierro** [comment]
Hi!

Thanks for taking the time to file an issue. The backend for the querybuilder had crashed in some weird state I haven't seen it in before. It has since been restarted, and the query builder seems to be working again. Can you give it a try now and let me know if you're still seeing the issue?

Thanks!

**Comment by rambalachandran** [comment]
@gtfierro yes I tested it and it works fine. Thank you. Also it would be helpful to know if there is any  community for mortar data or can I post my questions in the brick schema community (https://groups.google.com/forum/#!forum/brickschema).

**Comment by gtfierro** [comment]
Thanks!

There's a mailing list you can [subscribe to](https://lists.eecs.berkeley.edu/sympa/subscribe/mortar-users) and post questions to, but I'm going to try to set up a forum soon that the community will be able to use. If you subscribe to the mailing list, I will notify that list when the forum is ready to go
